schema_version = "1.0.0"

id = "rig_picker"

version = "1.0.0"

name = "Rig Picker"

tagline = "Floating Rig Picker"

maintainer = "Susmitha"

type = "add-on"

blender_version_min = "4.3.0"

license = [
    "SPDX:GPL-3.0-or-later",
]